Myambumy/forms/main.py
from flask_wtf import  FlaskForm
from wtforms import StringField,SubmitField,TextAreaField
from wtforms.validators import DataRequired,Length,Optional,Regexp
from flask_ckeditor import CKEditorField

#评论表单
class CommentForm(FlaskForm):
    body = TextAreaField('',validators=[DataRequired()])
    submit = SubmitField()

class DescriptionForm(FlaskForm):
    description = TextAreaField('Description', validators=[Optional(), Length(0, 500)])
    submit = SubmitField()


class TagForm(FlaskForm):
    tag = StringField('Add Tag (use space to separate)', validators=[Optional(), Length(0, 64)])
    submit = SubmitField()

class ArticleForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(1, 60)])
    tags = StringField('Category',validators=[DataRequired(), Length(1, 60),Regexp('^[\u4e00-\u9fa5#a-zA-Z0-9]+$',
                                                          message='The tag can contain only 字母 数字 汉字 #.')])
    content = CKEditorField('Content',validators=[DataRequired()])
    submit = SubmitField()

Myambumy/blueprints/ajax.py
# -*- coding: utf-8 -*-
"""
    :author: Grey Li (李辉)
    :url: http://greyli.com
    :copyright: © 2018 Grey Li <withlihui@gmail.com>
    :license: MIT, see LICENSE for more details.
"""
from flask import render_template, jsonify, Blueprint,request
from flask_login import current_user

from Myambumy.models import User, Photo, Notification,Article
from Myambumy.notifications import push_collect_notification, push_follow_notification,push_collect_notification_article

ajax_bp = Blueprint('ajax', __name__)


@ajax_bp.route('/notifications-count')
def notifications_count():
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403

    count = Notification.query.with_parent(current_user).filter_by(is_read=False).count()
    return jsonify(count=count)


@ajax_bp.route('/profile/<int:user_id>')
def get_profile(user_id):
    user = User.query.get_or_404(user_id)
    return render_template('main/profile_popup.html', user=user)


@ajax_bp.route('/followers-count/<int:user_id>')
def followers_count(user_id):
    user = User.query.get_or_404(user_id)
    count = user.followers.count() - 1  # minus user self
    return jsonify(count=count)


@ajax_bp.route('/<int:photo_id>/followers-count')
def collectors_count(photo_id):
    if request.args.get('type') == 'article':
        article = Article.query.get_or_404(photo_id)
        count = len(article.collectors)
    else:
        photo = Photo.query.get_or_404(photo_id)
        count = len(photo.collectors)
    return jsonify(count=count)


@ajax_bp.route('/collect/<int:photo_id>', methods=['POST'])
def collect(photo_id):
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403
    if not current_user.confirmed:
        return jsonify(message='Confirm account required.'), 400
    if not current_user.can('COLLECT'):
        return jsonify(message='No permission.'), 403
    if request.args.get('type') == 'article':
        article = Article.query.get_or_404(photo_id)
        if current_user.is_collecting_articles(article):
            return jsonify(message='Already collected.'), 400

        current_user.collect_article(article)
        if current_user != article.author and article.author.receive_collect_notification:
            push_collect_notification_article(collector=current_user, article_id=photo_id, receiver=article.author)
        return jsonify(message='Article collected.')
    else:
        photo = Photo.query.get_or_404(photo_id)
        if current_user.is_collecting(photo):
            return jsonify(message='Already collected.'), 400

        current_user.collect(photo)
        if current_user != photo.author and photo.author.receive_collect_notification:
            push_collect_notification(collector=current_user, photo_id=photo_id, receiver=photo.author)
        return jsonify(message='Photo collected.')


@ajax_bp.route('/uncollect/<int:photo_id>', methods=['POST'])
def uncollect(photo_id):
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403

    if request.args.get('type') == 'article':
        article = Article.query.get_or_404(photo_id)
        if not current_user.is_collecting_articles(article):
            return jsonify(message='Not collect yet.'), 400

        current_user.uncollect_article(article)
    else:
        photo = Photo.query.get_or_404(photo_id)
        if not current_user.is_collecting(photo):
            return jsonify(message='Not collect yet.'), 400

        current_user.uncollect(photo)

    return jsonify(message='Collect canceled.')


@ajax_bp.route('/follow/<username>', methods=['POST'])
def follow(username):
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403
    if not current_user.confirmed:
        return jsonify(message='Confirm account required.'), 400
    if not current_user.can('FOLLOW'):
        return jsonify(message='No permission.'), 403

    user = User.query.filter_by(username=username).first_or_404()
    if current_user.is_following(user):
        return jsonify(message='Already followed.'), 400

    current_user.follow(user)
    if user.receive_collect_notification:
        push_follow_notification(follower=current_user, receiver=user)
    return jsonify(message='User followed.')


@ajax_bp.route('/unfollow/<username>', methods=['POST'])
def unfollow(username):
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403

    user = User.query.filter_by(username=username).first_or_404()
    if not current_user.is_following(user):
        return jsonify(message='Not follow yet.'), 400

    current_user.unfollow(user)
    return jsonify(message='Follow canceled.')

Myambumy/blueprints/main.py
from flask import Blueprint,render_template,request,current_app,send_from_directory,flash,redirect,url_for,abort
from Myambumy.models import User,Photo,Comment,Tag,Collect,Article,Collect_article,Notification,Follow
from Myambumy.decorations import confirm_required,permission_required
from flask_login import  login_required,current_user
from Myambumy.utils import resize_image,rename_image,flash_errors
import os
from Myambumy.forms.main import CommentForm
from Myambumy.extensions import db
from Myambumy.forms.main import DescriptionForm,TagForm,ArticleForm
from sqlalchemy.sql.expression import func
from Myambumy.notifications import push_comment_notification,push_collect_notification,push_comment_notification_article
main_bp  = Blueprint('main',__name__)

@main_bp.route('/')
def index():
    if request.args.get('type') == 'article':
        if current_user.is_authenticated:
            page = request.args.get('page', 1, type=int)
            per_page = current_app.config['ALBUMY_PHOTO_PER_PAGE']
            pagination = Article.query \
                .join(Follow, Follow.followed_id == Article.author_id) \
                .filter(Follow.follower_id == current_user.id) \
                .order_by(Article.timestamp.desc()) \
                .paginate(page, per_page)
            articles = pagination.items
        else:
            pagination = None
            articles = None
        tags = Tag.query.join(Tag.articles).group_by(Tag.id).order_by(func.count(Article.id).desc()).limit(10)
        return render_template('main/index_article.html', pagination=pagination, articles=articles, tags=tags, Collect=Collect)

    else:
        if current_user.is_authenticated:
            page = request.args.get('page', 1, type=int)
            per_page = current_app.config['ALBUMY_PHOTO_PER_PAGE']
            pagination = Photo.query \
                .join(Follow, Follow.followed_id == Photo.author_id) \
                .filter(Follow.follower_id == current_user.id) \
                .order_by(Photo.timestamp.desc()) \
                .paginate(page, per_page)
            photos = pagination.items
        else:
            pagination = None
            photos = None
        tags = Tag.query.join(Tag.photos).group_by(Tag.id).order_by(func.count(Photo.id).desc()).limit(10)
        return render_template('main/index.html', pagination=pagination, photos=photos, tags=tags, Collect=Collect)


@main_bp.route('/explore')
def explore():
    photos = Photo.query.order_by(func.random()).limit(12)
    return render_template('main/explore.html', photos=photos)



@login_required
@confirm_required
@permission_required('UPLOAD')
@main_bp.route('/upload',methods=['GET','POST'])
def upload():
    if request.method == 'POST' and 'file' in request.files:
        f = request.files.get('file')
        filename = rename_image(f.filename)
        f.save(os.path.join(current_app.config['ALBUMY_UPLOAD_PATH'], filename))
        filename_s = resize_image(f, filename, current_app.config['ALBUMY_PHOTO_SIZE']['small'])
        filename_m = resize_image(f, filename, current_app.config['ALBUMY_PHOTO_SIZE']['medium'])
        photo = Photo(
            filename=filename,
            filename_s=filename_s,
            filename_m=filename_m,
            author=current_user._get_current_object()
        )
        db.session.add(photo)
        db.session.commit()
    return render_template('main/upload.html')

#返回对于的头像图片文件
@main_bp.route('/avatars/<path:filename>')
def get_avatar(filename):
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)

#用来返回图片
@main_bp.route('/uploads/<path:filename>')
def get_image(filename):
    return send_from_directory(current_app.config['ALBUMY_UPLOAD_PATH'], filename)

#收藏图片
@main_bp.route('/collect/<int:photo_id>',methods=['POST'])
@login_required
@confirm_required
@permission_required('COLLECT')
def collect(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    if current_user.is_collecting(photo):
        flash('Already collected.', 'info')
        return redirect(url_for('.show_photo', photo_id=photo_id))
    current_user.collect(photo)
    flash('Photo collected ','info')
    if current_user != photo.author:
        push_collect_notification(collector=current_user, photo_id=photo_id, receiver=photo.author)
    return redirect(url_for('.show_photo', photo_id=photo_id))

#收藏文章
@main_bp.route('/collect/article/<int:article_id>',methods=['POST'])
@login_required
@confirm_required
@permission_required('COLLECT')
def collect_article(article_id):
    article = Article.query.get_or_404(article_id)
    print("qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq",article.id)
    if current_user.is_collecting_articles(article):
        flash('Already collected.', 'info')
        return redirect(url_for('.show_article', article_id=article_id))
    current_user.collect_article(article)
    flash('Article collected ','info')
    return redirect(url_for('.show_article', article_id=article_id))


#取消收藏的图片
#下一步在photo_sider添加按钮
@main_bp.route('/uncollect/<int:photo_id>',methods=['POST'])
@login_required
def uncollect(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    if not current_user.is_collecting(photo):
        flash('Not collect yet.', 'info')
        return redirect(url_for('main.show_photo', photo_id=photo_id))

    current_user.uncollect(photo)
    flash('Photo uncollected.', 'info')
    return redirect(url_for('.show_photo', photo_id=photo_id))

#取消收藏文章
@main_bp.route('/uncollect/article/<int:article_id>',methods=['POST'])
@login_required
def uncollect_article(article_id):
    article = Article.query.get_or_404(article_id)
    if not current_user.is_collecting_articles(article):
        flash('Not collect yet.', 'info')
        return redirect(url_for('main.show_article', article_id=article_id))

    current_user.uncollect_article(article)
    flash('Article uncollected.', 'info')
    return redirect(url_for('.show_article', article_id=article_id))

#删除照片
@main_bp.route('/delete/photo/<int:photo_id>', methods=['POST'])
@login_required
def delete_photo(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    if current_user != photo.author:
        abort(403)
    db.session.delete(photo)
    db.session.commit()
    flash('Photo delete','info')

    photo_n = Photo.query.with_parent(photo.author).filter(Photo.timestamp < photo.timestamp).order_by(Photo.timestamp.desc()).first()
    if photo_n is None:
        photo_p = Photo.query.with_parent(photo.author).filter(Photo.timestamp > photo.timestamp).order_by(
            Photo.timestamp.asc()).first()

        if photo_p is None:
            return redirect(url_for('user.index',username=photo.author.username))
        return redirect(url_for('.show_photo',photo_id = photo_p.id))
    return redirect(url_for('.show_photo',photo_id = photo_n.id))


#展示收藏图片的界面
@main_bp.route('/photo/<int:photo_id>/collectors')
def show_collectors(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['ALBUMY_USER_PER_PAGE']
    pagination = Collect.query.with_parent(photo).order_by(Collect.timestamp.asc()).paginate(page, per_page)
    collects = pagination.items
    return render_template('main/collectors.html', collects=collects, photo=photo, pagination=pagination)

#展示文章收藏者界面
@main_bp.route('/photo/<int:article_id>/article/collectors')
def show_collectors_article(article_id):
    article = Article.query.get_or_404(article_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['ALBUMY_USER_PER_PAGE']
    pagination = Collect_article.query.with_parent(article).order_by(Collect_article.timestamp.asc()).paginate(page, per_page)
    collects = pagination.items
    return render_template('main/collectors_article.html', collects=collects, article=article, pagination=pagination)

@main_bp.route('/report/photo/<int:photo_id>',methods=['POST'])
@login_required
def report_photo(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    photo.flag+=1
    db.session.commit()
    flash('Photo reported ','success')
    return redirect(url_for('.show_photo',photo_id=photo_id))
#图片向前翻页
@main_bp.route('/photo_previous/<int:photo_id>')
def photo_previous(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    photo_p = Photo.query.with_parent(photo.author).filter(Photo.timestamp > photo.timestamp).order_by(Photo.timestamp.asc()).first()
    if photo_p is None:
        flash('This is already the first one.', 'info')
        return redirect(url_for('.show_photo', photo_id=photo_id))
    return redirect(url_for('.show_photo', photo_id=photo_p.id))

#图片向后翻页，按显示界面顺序
@main_bp.route('/photo_next/<int:photo_id>')
def photo_next(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    #photo_n  = Photo.query.with_parent(photo.author).filter(Photo.id < photo.id).order_by(Photo.id.desc()).first()
    #按时间排序更符合实际
    photo_n = Photo.query.with_parent(photo.author).filter(Photo.timestamp < photo.timestamp).order_by(Photo.timestamp.desc()).first()
    if photo_n is None:
        flash('This is already the last one.', 'info')
        return redirect(url_for('.show_photo', photo_id=photo_id))
    return redirect(url_for('.show_photo',photo_id = photo_n.id))

#修改描述
@main_bp.route('/photo/<int:photo_id>/description',methods=['POST'])
def edit_description(photo_id):
    photo = Photo.query.get_or_404(photo_id)
    if current_user != photo.author:
        abort(403)
    form = DescriptionForm()
    if form.validate_on_submit():
        photo.description = form.description.data
        db.session.commit()
        flash('Description updated','success')
    flash_errors(form)
    return redirect(url_for('.show_photo',photo_id=photo_id))


Myambumy/templates/main/_article_sidebar.html
<div class="card bg-light mb-3 w-100 sidebar-card">
    <div class="card-body">
        <div class="row">
            <a href="{{ url_for('user.index', username=article.author.username) }}">
                <img class="sidebar-avatar rounded avatar-m"
                     src="{{ url_for('main.get_avatar', filename=article.author.avatar_m) }}">
            </a>
            <div class="sidebar-profile">
                <h6 class="card-title">
                    <a href="{{ url_for('user.index', username=article.author.username) }}">{{ article.author.name }}</a>
                </h6>
                <p class="card-subtitle mb-2 text-muted">{{ article.author.username }}</p>
            </div>
        </div>
    </div>
</div>

<div class="card bg-light mb-3 w-100">
    <div class="card-body">
        <div id="tags">
            <p>
                {% if article.tags %}
                    <h3>Tags:</h3>
                    {% for tag in article.tags %}
                        <a class="badge badge-light"
                           href="{{ url_for('.show_tag', tag_id=tag.id,type='article') }}" target="_blank"><span
                                class="oi oi-tag"></span> {{ tag.name }}</a>
                    {% endfor %}
                {% endif %}
                {% if current_user == article.author %}
                    <a id="tag-btn" href="#!">
                        <small><span class="oi oi-pencil"></span> edit tag</small>
                    </a>
                {% endif %}
            </p>
        </div>
        {% if current_user == article.author %}
            <div id="tag-form">
                <form action="{{ url_for('.new_tag2', photo_id=article.id,type='article') }}" method="post">
                    {{ tag_form.csrf_token }}
                    {{ render_field(tag_form.tag) }}
                    <a class="btn btn-light btn-sm" id="cancel-tag">Cancel</a>
                    {{ render_field(tag_form.submit, class='btn btn-success btn-sm') }}
                </form>
                {% if article.tags %}
                    <hr>
                    {% for tag in article.tags %}
                        <a class="dead-link" href="#!"
                           data-href="{{ url_for('.delete2_tag', photo_id=article.id, tag_id=tag.id,type='article') }}"
                           data-toggle="modal" data-target="#confirm-delete" title="Delete tag">
                <span class="badge badge-danger">
                {{ tag.name }} <span class="oi oi-trash" aria-hidden="true"></span>
            </span>
                        </a>
                    {% endfor %}
                {% endif %}
            </div>
        {% endif %}

        {% if current_user.is_authenticated %}
            {% if current_user.is_collecting_articles(article) %}
                <form class="inline" method="post"
                      action="{{ url_for('main.uncollect_article', article_id=article.id) }}">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <button type="submit" class="btn btn-outline-secondary btn-sm">
                        <span class="oi oi-x"></span> Uncollect
                    </button>
                </form>
            {% else %}
                <form class="inline" method="post"
                      action="{{ url_for('main.collect_article', article_id=article.id) }}">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <button type="submit" class="btn btn-outline-primary btn-sm">
                        <span class="oi oi-star"></span> Collect
                    </button>
                </form>
            {% endif %}
        {% else %}
            <form class="inline" method="post" action="{{ url_for('main.collect_article', article_id=article.id) }}">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <button type="submit" class="btn btn-primary btn-sm">
                    <span class="oi oi-star"></span> Collect
                </button>
            </form>
        {% endif %}

        {% if article.collectors %}
            <a href="{{ url_for('main.show_collectors_article', article_id=article.id) }}">{{ article.collectors|length }}
                collectors</a>
        {% endif %}
    </div>
</div>

Myambumy/templates/main/_sidebar.html
<div class="card bg-light mb-3 w-100 sidebar-nav">
    <div class="card-body">
        <div class="row">
            <a href="{{ url_for('user.index', username=current_user.username) }}">
                <img class="rounded avatar-s" style="margin-left: 15px; position: absolute"
                     src="{{ url_for('main.get_avatar', filename=current_user.avatar_m) }}">
            </a>
            <div class="sidebar-nav-name">
                <h6 class="card-title"><a
                        href="{{ url_for('user.index', username=current_user.username) }}">{{ current_user.name }}
                </a></h6>
                <p class="card-subtitle mb-2 text-muted">{{ current_user.username }}</p>
            </div>
        </div>
        <a class="card-link" href="{{ url_for('user.index', username=current_user.username) }}">
            <span class="oi oi-home"></span> My Home
        </a><br>
        <a class="card-link" href="{{ url_for('user.show_collections', username=current_user.username) }}">
            <span class="oi oi-star"></span> My Collections
        </a>
    </div>
</div>
<div class="card bg-light mb-3 w-100">
    <div class="card-header">Hot Tags</div>
    <div class="list-group">
        {% for tag in tags %}
            <a class="list-group-item" href="{{ url_for('.show_tag', tag_id=tag.id) }}">{{ tag.name }}
                <span class="badge badge-pill">{{ tag.photos|length }}</span>
            </a>
        {% endfor %}
    </div>
</div>

Myambumy/templates/main/create_article.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% block title %}New Article{% endblock %}
{% block content %}
    <div class="page-header">
        <h1>New Article</h1>
        {{ render_form(form) }}
    </div>

{% endblock %}
{% block scripts %}
    {{ super() }}
    <script type="text/javascript" src="{{ url_for('static', filename='ckeditor/ckeditor.js') }}"></script>
{% endblock %}

Myambumy/templates/main/index_article.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import article_card with context %}

{% block title %}Home{% endblock %}

{% block content %}
{% if current_user.is_authenticated %}
    <a href="{{ url_for('main.index') }}"><span>Photo </span>  |</a>
    <a href="{{ url_for('main.index', type='article') }}"><span > Articles </span> </a>
    <hr>
    <div class="row justify-content-md-center">
        <div class="col-md-8">
            {% if articles %}
                {% for article in articles %}
                    <div class="card mb-3 w-100 bg-light">
                        <div class="card-header">
                            <a class="dead-link" href="{{ url_for('user.index', username=article.author.username) }}">
                                <img class="rounded img-fluid avatar-s profile-popover"
                                     data-href="{{ url_for('ajax.get_profile', user_id=article.author.id) }}"
                                     src="{{ url_for('main.get_avatar', filename=article.author.avatar_m) }}">
                            </a>
                            <a class="profile-popover trend-card-avatar"
                               data-href="{{ url_for('ajax.get_profile', user_id=article.author.id) }}"
                               href="{{ url_for('user.index', username=article.author.username) }}">{{ article.author.name }}</a>
                            <span class="float-right">
                <small data-toggle="tooltip" data-placement="top" data-timestamp="{{ article.timestamp }}"
                       data-delay="500">
                    {{ moment(article.timestamp).fromNow(refresh=True) }}</small></span>
                        </div>
                        <div class="card-body">
                            <div class="" align="center">
                                <div >
                                 <h3 class="text-primary"><a href="{{ url_for('main.show_article', article_id=article.id) }}">{{ article.title }}</a></h3>
                                     <p>
                                         {{ article.content|striptags|truncate }}
                                        <small><a href="{{ url_for('main.show_article', article_id=article.id) }}">Read More</a></small>
                                     </p>

                            </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <span class="oi oi-star"></span>

                            <span id="collectors-count-{{ article.id }}"
                                  data-href="{{ url_for('ajax.collectors_count', photo_id=article.id,type='article') }}">
                                {{ article.collectors|length }}
                            </span>
                            <span class="oi oi-comment-square"></span> {{ article.comments|length }}
                                &nbsp;&nbsp;&nbsp;
                                <span>
                                    {% if article.tags %}
                                        {% for tag in article.tags %}
                                <a class="badge badge-light"
                                href="{{ url_for('.show_tag', tag_id=tag.id) }}" target="_blank"><span
                                class="oi oi-tag"></span> {{ tag.name }}</a>
                                        {% endfor %}
                                    {% endif %}

                                    </span>

                            <div class="float-right">
                                {% if current_user.is_authenticated %}
                                    <button class="{% if not current_user.is_collecting(article) %}hide{% endif %}
                                     btn btn-outline-secondary btn-sm uncollect-btn"
                                            data-href="{{ url_for('ajax.uncollect', photo_id=article.id,type='article') }}"
                                            data-id="{{ article.id }}">
                                        <span class="oi oi-x"></span> Uncollect
                                    </button>
                                    <button class="{% if current_user.is_collecting(article) %}hide{% endif %}
                                     btn btn-outline-primary btn-sm collect-btn"
                                            data-href="{{ url_for('ajax.collect', photo_id=article.id,type='article') }}"
                                            data-id="{{ article.id }}">
                                        <span class="oi oi-star"></span> Collect
                                    </button>
                                {% else %}
                                    <form class="inline" method="post"
                                          action="{{ url_for('main.collect_article', article_id=article.id) }}">
                                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-outline-primary btn-sm">
                                            <span class="oi oi-star"></span> Collect
                                        </button>
                                    </form>
                                {% endif %}
                            </div>

                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="tip text-center">
                    <h3>No trends.</h3>
                    <p><a href="{{ url_for('.explore') }}">Explore</a></p>
                </div>
            {% endif %}
        </div>
        <div class="col-md-3">
            {% include 'main/index_article_sidebar.html' %}
        </div>
    </div>
    {% if articles %}
        {{ render_pagination(pagination, align='center') }}
    {% endif %}
{% else %}
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-8">
                <img src="{{ url_for('static', filename='images/index.jpg') }}" class="rounded img-fluid">
            </div>
            <div class="col-md-4 align-self-center">
                <h1>Albumy</h1>
                <p>Capture and remember every wonderful moment.</p>
                <p><a class="btn btn-primary btn-lg" href="{{ url_for('auth.register') }}">Join Now</a></p>
            </div>
        </div>
    </div>
{% endif %}
{% endblock %}

Myambumy/templates/main/profile_popup.html
<div class="popup-card">
    <img class="rounded img-fluid avatar-s popup-avatar" src="{{ url_for('main.get_avatar', filename=user.avatar_m) }}">
    <div class="popup-profile">
        <h6>{{ user.name }}</h6>
        <p class="text-muted">{{ user.username }}
            {% if current_user.is_authenticated %}
                {% if current_user != user and current_user.is_followed_by(user) %}
                    {% if user.is_followed_by(current_user) %}
                        <span class="badge badge-light">Follow each other</span>
                    {% else %}
                        <span class="badge badge-light">Follows you</span>
                    {% endif %}
                {% endif %}
            {% endif %}
        </p>
    </div>
    <p class="card-text">
        <a href="{{ url_for('user.index', username=user.username) }}">
            <strong>{{ user.photos|length }}</strong> Photos
        </a>&nbsp;
        <a href="{{ url_for('user.show_followers', username=user.username) }}">
            <strong id="followers-count-{{ user.id }}"
                    data-href="{{ url_for('ajax.followers_count', user_id=user.id) }}">
                {{ user.followers.count() - 1 }}
            </strong> Followers
        </a>
    </p>
    <a href="{{ url_for('user.index', username=user.username) }}" class="btn btn-light btn-sm">Homepage</a>
    {% if current_user.is_authenticated %}
        {% if user != current_user %}
            <button data-id="{{ user.id }}"
                    data-href="{{ url_for('ajax.unfollow', username=user.username) }}"
                    class="{% if not current_user.is_following(user) %}hide{% endif %} btn btn-dark btn-sm unfollow-btn">
                Unfollow
            </button>
            <button data-id="{{ user.id }}"
                    data-href="{{ url_for('ajax.follow', username=user.username) }}"
                    class="{% if current_user.is_following(user) %}hide{% endif %} btn btn-primary btn-sm follow-btn">
                Follow
            </button>
        {% endif %}
    {% else %}
        <form class="inline" method="post"
              action="{{ url_for('user.follow', username=user.username) }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <button type="submit" class="btn btn-primary btn-sm">Follow</button>
        </form>
    {% endif %}
</div>